In [26]:
from keras.preprocessing.image import img_to_array
from keras.models import load_model
import numpy as np
import imutils
import pickle
import cv2
import os

In [27]:
def prediction(file_path, model, mlb):
    image = cv2.imread(file_path)

    # pre-process the image for classification
    image = cv2.resize(image, (96, 96))
    image = image.astype("float") / 255.0
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)

#     model = load_model('pose_multi_labels.h5')
#     mlb = pickle.loads(open('mlb.pickle', "rb").read())

    proba = model.predict(image)[0]
    idxs = np.argsort(proba)[::-1][:2]
    print(idxs)
    # build the label and draw the label on the image
    label = "{}_{}".format(mlb.classes_[idxs[0]], mlb.classes_[idxs[1]])
    
    return label

# print(prediction(image_path))

In [28]:
model = load_model('pose_multi_labels.h5')
mlb = pickle.loads(open('mlb.pickle', "rb").read())

def get_files_path(path, file_extension):
    file_content = []
    for root, dirs, files in os.walk(path):
        for file in files:
            lower_file = file.lower()
            if lower_file.endswith(file_extension):
                file_path = os.path.join(path, file)
                file_content.append(file_path)
        break
    return file_content

files = get_files_path('./dataset/test_set/bending_h', '.jpg')

for f in files:
    print(prediction(f, model, mlb))

[0 2]
bending_h
[0 2]
bending_h
[0 2]
bending_h
[0 2]
bending_h
[1 3]
crouching_n
[4 2]
others_h
[0 2]
bending_h
[0 2]
bending_h
[0 3]
bending_n
[2 0]
h_bending
[3 2]
n_h
[0 2]
bending_h
[2 0]
h_bending
[0 2]
bending_h
[0 2]
bending_h
[2 0]
h_bending
[0 2]
bending_h
[0 2]
bending_h
[0 2]
bending_h
[0 2]
bending_h
[0 2]
bending_h
[0 2]
bending_h
[0 2]
bending_h
[0 2]
bending_h
[0 2]
bending_h
[2 0]
h_bending
[2 0]
h_bending
[0 2]
bending_h
[0 2]
bending_h
[2 0]
h_bending


In [30]:
files = get_files_path('./dataset/test_set/others_h', '.jpg')
print(len(files))
for f in files:
    print(prediction(f, model, mlb))

30
[2 4]
h_others
[2 4]
h_others
[1 3]
crouching_n
[2 4]
h_others
[2 1]
h_crouching
[4 3]
others_n
[4 2]
others_h
[2 5]
h_standing
[4 3]
others_n
[4 2]
others_h
[2 4]
h_others
[2 4]
h_others
[2 4]
h_others
[4 2]
others_h
[2 4]
h_others
[2 4]
h_others
[2 4]
h_others
[2 4]
h_others
[4 2]
others_h
[2 4]
h_others
[2 4]
h_others
[4 2]
others_h
[2 4]
h_others
[2 4]
h_others
[2 4]
h_others
[2 4]
h_others
[4 2]
others_h
[2 4]
h_others
[2 1]
h_crouching
[4 2]
others_h


In [4]:
image_path = './dataset/test_set/bending_h/13_20180502093101_0090_0.jpg'

image = cv2.imread(image_path)

# pre-process the image for classification
image = cv2.resize(image, (96, 96))
image = image.astype("float") / 255.0
image = img_to_array(image)
image = np.expand_dims(image, axis=0)

model = load_model('pose_multi_labels.h5')
mlb = pickle.loads(open('mlb.pickle', "rb").read())

proba = model.predict(image)[0]
idxs = np.argsort(proba)[::-1][:2]

print(idxs)

[[[101  91  67]
  [140 125  99]
  [172 141 116]
  ...
  [141 134 131]
  [146 139 136]
  [159 154 151]]

 [[154 141 119]
  [147 129 106]
  [149 118  93]
  ...
  [155 148 145]
  [154 149 146]
  [158 153 152]]

 [[157 141 125]
  [148 126 108]
  [153 121  98]
  ...
  [150 145 144]
  [152 148 147]
  [155 150 151]]

 ...

 [[163 168 167]
  [161 166 165]
  [153 155 155]
  ...
  [147 153 152]
  [147 153 152]
  [147 153 152]]

 [[166 171 170]
  [163 168 167]
  [154 156 156]
  ...
  [148 154 153]
  [148 154 153]
  [148 154 153]]

 [[164 169 168]
  [164 169 168]
  [157 159 159]
  ...
  [149 155 154]
  [149 155 154]
  [150 156 155]]]
[0 2]


In [9]:
np.set_printoptions(suppress=True)
print(proba)
# loop over the indexes of the high confidence class labels
for (i, j) in enumerate(idxs):
    # build the label and draw the label on the image
    label = "{}: {:.2f}%".format(mlb.classes_[j], proba[j] * 100)
    print(label)

[0.97122014 0.00064212 0.6162123  0.3793038  0.00011762 0.04957826]
0 0
bending: 97.12%
1 2
h: 61.62%


In [8]:
# show the probabilities for each of the individual labels
for (label, p) in zip(mlb.classes_, proba):
    print("{}: {:.2f}%".format(label, p * 100))

bending: 97.12%
crouching: 0.06%
h: 61.62%
n: 37.93%
others: 0.01%
standing: 4.96%
